# Generated by Django 5.1.1 on 2025-02-19 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllDart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcept_dt', models.DateTimeField()),
                ('corp_cls', models.CharField(max_length=4)),
                ('corp_name', models.CharField(max_length=30, null=True)),
                ('rcept_no', models.CharField(max_length=18)),
                ('report_nm', models.CharField(max_length=100)),
                ('stock_code', models.CharField(max_length=7, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alldart_set', to='api.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='DartBonusIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcept_dt', models.DateTimeField(null=True)),
                ('신주의수', models.IntegerField(null=True)),
                ('주당배정주식수', models.FloatField(null=True)),
                ('배당기산일', models.DateTimeField(null=True)),
                ('상장예정일', models.DateTimeField(null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dartbonusissue_set', to='api.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='DartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcept_dt', models.DateTimeField(null=True)),
                ('계약내용', models.CharField(max_length=30, null=True)),
                ('계약금액', models.BigIntegerField(null=True)),
                ('계약상대방', models.CharField(max_length=30, null=True)),
                ('공급지역', models.CharField(max_length=30, null=True)),
                ('매출액대비', models.FloatField(null=True)),
                ('계약기간_시작', models.DateTimeField(null=True)),
                ('계약기간_종료', models.DateTimeField(null=True)),
                ('계약기간일', models.IntegerField(null=True)),
                ('계약일', models.DateTimeField(null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dartcontract_set', to='api.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='DartConvertibleBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('rcept_dt', models.DateTimeField(null=True)),
                ('전환사채총액', models.BigIntegerField(null=True)),
                ('자금조달목적', models.CharField(max_length=30, null=True)),
                ('표면이자율', models.FloatField(null=True)),
                ('만기이자율', models.FloatField(null=True)),
                ('전환가액', models.FloatField(null=True)),
                ('전환청구시작일', models.DateTimeField(null=True)),
                ('전환청구종료일', models.DateTimeField(null=True)),
                ('발행주식수', models.IntegerField(null=True)),
                ('주식총수대비비율', models.FloatField(null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dartconvertiblebond_set', to='api.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='DartRightsIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcept_dt', models.DateTimeField(null=True)),
                ('증자방식', models.CharField(max_length=30, null=True)),
                ('신주의수', models.IntegerField(null=True)),
                ('증자전주식수', models.IntegerField(null=True)),
                ('신주비율', models.FloatField(null=True)),
                ('자금조달목적', models.CharField(max_length=30, null=True)),
                ('발행가액', models.FloatField(null=True)),
                ('납입일', models.DateTimeField(null=True)),
                ('배당기산일', models.DateTimeField(null=True)),
                ('상장예정일', models.DateTimeField(null=True)),
                ('제3자배정대상자', models.CharField(max_length=30, null=True)),
                ('제3자배정대상자관계', models.CharField(max_length=30, null=True)),
                ('제3자배정대상자선정경위', models.TextField(null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dartrightsissue_set', to='api.ticker')),
            ],
        ),
    ]
