# Generated by Django 5.1.1 on 2025-02-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alldart_dartbonusissue_dartcontract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dartbonusissue',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dartcontract',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dartrightsissue',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
