# Generated by Django 5.1.1 on 2025-02-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dartbonusissue_name_dartcontract_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dartbonusissue',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dartcontract',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dartcontract',
            name='계약내용',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dartcontract',
            name='계약상대방',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dartcontract',
            name='공급지역',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dartconvertiblebond',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dartrightsissue',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dartrightsissue',
            name='증자방식',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
