# Generated by Django 5.1.1 on 2025-02-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dartbonusissue_name_alter_dartcontract_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dartconvertiblebond',
            name='자금조달목적',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dartrightsissue',
            name='자금조달목적',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dartrightsissue',
            name='제3자배정대상자',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dartrightsissue',
            name='제3자배정대상자관계',
            field=models.TextField(null=True),
        ),
    ]
