# Generated by Django 5.1.1 on 2025-02-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='buy_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
