# Generated by Django 5.1.1 on 2025-02-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_favorite_buy_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ['change_date', 'change_field'], 'verbose_name': '데이터변경', 'verbose_name_plural': '데이터변경 목록'},
        ),
        migrations.AlterModelOptions(
            name='dartbonusissue',
            options={'verbose_name': '무상증자', 'verbose_name_plural': '무상증자 목록'},
        ),
        migrations.AlterModelOptions(
            name='dartcontract',
            options={'verbose_name': '공급계약', 'verbose_name_plural': '공급계약 목록'},
        ),
        migrations.AlterModelOptions(
            name='dartconvertiblebond',
            options={'verbose_name': '전환사채', 'verbose_name_plural': '전환사채 목록'},
        ),
        migrations.AlterModelOptions(
            name='dartrightsissue',
            options={'verbose_name': '유상증자', 'verbose_name_plural': '유상증자 목록'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Infos'},
        ),
        migrations.AlterModelOptions(
            name='iss',
            options={'verbose_name': '이슈', 'verbose_name_plural': '이슈 목록'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '뉴스', 'verbose_name_plural': '뉴스 목록'},
        ),
        migrations.AlterModelOptions(
            name='ohlcv',
            options={'ordering': ['Date'], 'verbose_name': 'OHLCV', 'verbose_name_plural': 'OHLCVs'},
        ),
    ]
