# Generated by Django 5.1.1 on 2025-02-26 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_changelog_options_alter_dartbonusissue_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='buy_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'ticker'], name='api_favorit_user_id_412b80_idx'),
        ),
    ]
