# Generated by Django 5.1.1 on 2025-02-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_aiopinion_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiopinion',
            name='ai_method',
            field=models.CharField(default='openai', max_length=20),
            preserve_default=False,
        ),
    ]
