# Generated by Django 5.1.1 on 2025-03-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_aiopinionforstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='dartbonusissue',
            name='rcept_no',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='dartcontract',
            name='rcept_no',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='dartconvertiblebond',
            name='rcept_no',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='dartrightsissue',
            name='rcept_no',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
