# Generated by Django 5.1.1 on 2025-05-27 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_aiopinionforstock_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('공매도', models.BigIntegerField(null=True)),
                ('매수', models.BigIntegerField(null=True)),
                ('비중', models.FloatField(null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_set', to='api.ticker')),
            ],
        ),
        migrations.CreateModel(
            name='ShortInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('대차체결주식수', models.BigIntegerField(null=True)),
                ('리콜상환주식수', models.BigIntegerField(null=True)),
                ('상환주식수', models.BigIntegerField(null=True)),
                ('대차잔여주식수', models.BigIntegerField(null=True)),
                ('대차잔액', models.BigIntegerField(null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_interest_set', to='api.ticker')),
            ],
        ),
    ]
