# Generated by Django 5.1.1 on 2025-03-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership',
            field=models.CharField(choices=[('SPECIAL', '특별회원'), ('REGULAR', '정회원'), ('ASSOCIATE', '준회원')], default='ASSOCIATE', max_length=10, verbose_name='회원등급'),
        ),
    ]
